import React from 'react';
import PoketmonPNG from '../assets/images/poketmon.png';
import PokeballPNG from '../assets/images/pokeball.png';
import FemalePNG from '../assets/images/female.png';
import MalePNG from '../assets/images/male.png';
import PikaPNG from '../assets/images/pika.png';
import GrassPNG from '../assets/images/grass.png';
import PoisonJPG from '../assets/images/poison.jpg';
import FirePNG from '../assets/images/fire.png';
import GhostJPG from '../assets/images/ghost.jpg';
import RockJPG from '../assets/images/rock.jpg';
import EspJPG from '../assets/images/esp.jpg';
import FightJPG from '../assets/images/fight.jpg';
import IceJPG from '../assets/images/ice.jpg';
import EarthJPG from '../assets/images/earth.jpg';
import ElectricJPG from '../assets/images/electric.jpg';
import SteelPNG from '../assets/images/steel.png';
import NomalPNG from '../assets/images/nomal.png';
import WaterPNG from '../assets/images/water.png';
import InsectJPG from '../assets/images/insect.jpg';
import DragonJPG from '../assets/images/dragon.jpg';
import FlyingJPG from '../assets/images/flying.jpg';
import BubblePNG from '../assets/images/bubble_off.png';

export const Poketmon = PoketmonPNG;
export const Pokeball = PokeballPNG;
export const Female = FemalePNG;
export const Male = MalePNG;
export const Pika = PikaPNG;
export const Grass = GrassPNG;
export const Poison = PoisonJPG;
export const Fire = FirePNG;
export const Ghost = GhostJPG;
export const Rock = RockJPG;
export const Esp = EspJPG;
export const Fight = FightJPG;
export const Ice = IceJPG;
export const Earth = EarthJPG;
export const Electric = ElectricJPG;
export const Steel = SteelPNG;
export const Nomal = NomalPNG;
export const Water = WaterPNG;
export const Insect = InsectJPG;
export const Dragon = DragonJPG;
export const Flying = FlyingJPG;
export const Bubble = BubblePNG;
